config/routes.rb
# frozen_string_literal: true

require 'resque/scheduler/server'
require 'resque/server'

Rails.application.routes.draw do
  authenticated :user, ->(u) {u.admin?} do
    mount Resque::Server.new, at: '/resque'
  end

  get :oauth2callback, to: 'system_settings#oauth2_store_credential'

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'channels#index'
    devise_for :users

    resource :system_setting, except: :destroy do
      member do
        put :oauth2_store_credential
      end
    end
    resources :channels, only: [:index, :show] do
      member do
        put :build_statistics
        put :update_snippet
        put :enable
        put :disable
      end
      collection do
        put :build_all_statistics
        put :update_all_snippets
      end
      scope module: :channels do
        resources :snippets, only: [:index]
        resources :statistics, only: [:index]
      end
    end

    authenticated :user, ->(u) {u.admin?} do
      namespace :channel_lists do
        resources :search, only: [:index, :create]
        resources :subscriptions, only: [:index, :create]
      end

      resources :channels, only: [] do
        scope module: :channels do
          resource :tags, only: [:edit, :update]
        end
      end

      resources :tags, only: :index
    end
  end
end

app/models/channel.rb
# frozen_string_literal: true

class Channel < ApplicationRecord
  include SystemSettingAware

  has_many :channel_statistics, -> {order(created_at: :desc)},
           dependent: :destroy, inverse_of: :channel
  has_many :channel_snippets, -> {order(created_at: :desc)},
           dependent: :destroy, inverse_of: :channel

  validates :channel_id, presence: {message: proc {I18n.t('text.channel.channel_id.invalid')}}
  validates :channel_id, uniqueness: true
  validates :thumbnail_url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https]),
                            allow_blank: true

  acts_as_taggable_on :tags

  DEFAULT_PER = 50
  MAX_PER = 100
  PER_LIST = [5, 10, 20, DEFAULT_PER, 75, MAX_PER].freeze

  def save_and_set_job
    return false unless save

    JobUtils.enqueue(Channels::BuildStatisticsJob, 'channel_id' => id)
    JobUtils.enqueue(Channels::UpdateSnippetJob, 'channel_id' => id)
    true
  end

  def url
    "https://www.youtube.com/channel/#{channel_id}"
  end

  def build_statistics!
    res = youtube_service.statistics(channel_id)
    raise res.error if res.error.present?

    statistics = res.response
    channel_statistics.create!(channel_statistics_params(statistics))
  end

  def update_latest_statistics!(channel_statistics)
    prev_view_count = latest_view_count
    prev_subscriber_count = latest_subscriber_count
    prev_video_count = latest_video_count
    prev_acquired_at = latest_acquired_at
    update!(
      second_latest_view_count: prev_view_count,
      second_latest_subscriber_count: prev_subscriber_count,
      second_latest_video_count: prev_video_count,
      second_latest_acquired_at: prev_acquired_at,
      latest_view_count: channel_statistics.view_count,
      latest_subscriber_count: channel_statistics.subscriber_count,
      latest_video_count: channel_statistics.video_count,
      latest_acquired_at: channel_statistics.created_at
    )
  end

  def update_snippet!
    res = youtube_service.snippet(channel_id)
    raise res.error if res.error.present?

    snippet = res.response
    self.attributes = snippet_params(snippet)
    return unless has_changes_to_save?

    channel_snippets.create!(channel_snippet_params(snippet))
    save!
  end

  def youtube_service
    return @youtube_service if @youtube_service
    raise t('text.system_setting.missing') unless system_setting

    @youtube_service = system_setting.youtube_service
  end

  def channel_id=(val)
    super(parse_channel_id(val))
  end

  def medium_thumbnail_url
    thumbnail_url&.gsub('s88-', 's240-')
  end

  def high_thumbnail_url
    thumbnail_url&.gsub('s88-', 's800-')
  end

  def enabled?
    !disabled?
  end

  def tag_list_json
    tag_list.map {|tag| {value: tag}}.to_json
  end

  private

  def parse_channel_id(val)
    uri = URI.parse(val)
    if (m = uri.path.match(Consts::Youtube::REGEXP_URL))
      m[:channel_id]
    end
  rescue URI::InvalidURIError
    nil
  end

  def snippet_params(snippet)
    {
      title: snippet.title,
      description: snippet.description,
      thumbnail_url: snippet.thumbnails.default.url,
      published_at: snippet.published_at
    }
  end

  def channel_snippet_params(snippet)
    {
      title: snippet.title,
      description: snippet.description,
      thumbnail_url: snippet.thumbnails.default.url
    }
  end

  def channel_statistics_params(statistics)
    {
      view_count: statistics.view_count,
      subscriber_count: statistics.hidden_subscriber_count ? 0 : statistics.subscriber_count,
      video_count: statistics.video_count
    }
  end
end

app/models/search/channel.rb
# frozen_string_literal: true

module Search
  class Channel < Search::Base
    attr_accessor :ids, :title, :tag
    attr_writer :disabled, :from_date, :to_date, :subscriber_count_from, :subscriber_count_to,
                :video_count_from, :video_count_to, :view_count_from, :view_count_to

    def search
      ret = ::Channel.preload(:tags)
      ret = ret.where(id: ids) if ids.present?
      ret = ret.where("title LIKE ? ESCAPE '\\'", "%#{::Channel.sanitize_sql_like(title)}%") if title.present?
      ret = ret.where(published_at: published_at) if published_at.present?
      ret = ret.where(disabled: disabled) unless disabled.nil?
      ret = ret.where(latest_subscriber_count: subscriber_count) if subscriber_count.present?
      ret = ret.where(latest_video_count: video_count) if video_count.present?
      ret = ret.where(latest_view_count: view_count) if view_count.present?
      ret = ret.tagged_with("'#{tag}'") if tag.present?
      ret = ret.order(sort_column)
      ret = ret.reverse_order if direction == 'desc' || direction.nil?
      ret.paginate(per: per, page: page)
    end

    def disabled
      return if @disabled.nil? || @disabled == ''

      @disabled
    end

    def from_date
      Date.parse(@from_date.to_s).beginning_of_day
    rescue TypeError, Date::Error
      nil
    end

    def to_date
      Date.parse(@to_date.to_s).end_of_day
    rescue TypeError, Date::Error
      nil
    end

    def published_at
      return if from_date.nil? && to_date.nil?

      from_date..to_date
    end

    def subscriber_count_from
      @subscriber_count_from.presence&.to_i
    end

    def subscriber_count_to
      @subscriber_count_to.presence&.to_i
    end

    def subscriber_count
      return if subscriber_count_from.nil? && subscriber_count_to.nil?

      subscriber_count_from..subscriber_count_to
    end

    def video_count_from
      @video_count_from.presence&.to_i
    end

    def video_count_to
      @video_count_to.presence&.to_i
    end

    def video_count
      return if video_count_from.nil? && video_count_to.nil?

      video_count_from..video_count_to
    end

    def view_count_from
      @view_count_from.presence&.to_i
    end

    def view_count_to
      @view_count_to.presence&.to_i
    end

    def view_count
      return if view_count_from.nil? && view_count_to.nil?

      view_count_from..view_count_to
    end

    def self.disabled_options
      {
        I18n.t('activemodel.attributes.search.disabled_options.both') => nil,
        I18n.t('activemodel.attributes.search.disabled_options.enabled_only') => false,
        I18n.t('activemodel.attributes.search.disabled_options.disabled_only') => true
      }
    end

    private

    def sort_column
      case order
      when 'title', 'published_at'
        order.to_sym
      when 'view_count', 'subscriber_count', 'video_count', 'latest_acquired_at'
        "latest_#{order}"
      else
        'latest_subscriber_count'
      end
    end
  end
end

app/controllers/channels/snippets_controller.rb
# frozen_string_literal: true

module Channels
  class SnippetsController < ApplicationController
    before_action :set_channel

    def index
      return redirect_to channel_path(@channel) unless turbo_frame_request?

      channel_snippets = @channel.channel_snippets
                                 .paginate(page: params[:page], per: 5)
                                 .padding(1) # Do not fetch the latest one
      render partial: 'channels/snippets_frame', locals: {channel_snippets: channel_snippets}
    end

    private

    def set_channel
      @channel = Channel.find(params[:channel_id])
    end
  end
end

app/controllers/channels/statistics_controller.rb
# frozen_string_literal: true

module Channels
  class StatisticsController < ApplicationController
    before_action :set_channel

    def index
      return redirect_to channel_path(@channel) unless turbo_frame_request?

      channel_statistics = @channel.channel_statistics.paginate(page: params[:page], per: params[:per])
      render partial: 'channels/statistics_frame', locals: {channel_statistics: channel_statistics}
    end

    private

    def set_channel
      @channel = Channel.find(params[:channel_id])
    end
  end
end

app/controllers/channels/tags_controller.rb
# frozen_string_literal: true

module Channels
  class TagsController < ApplicationController
    before_action :set_channel

    def edit
      render partial: 'form_tag_list', locals: {channel: @channel}
    end

    def update
      if set_tag_list(@channel) && @channel.save
        redirect_to @channel, notice: t('text.channel.update_tags.success')
      else
        redirect_to @channel, alert: t('text.channel.update_tags.error')
      end
    end

    private

    def set_channel
      @channel = Channel.find(params[:channel_id])
    end

    def set_tag_list(channel) # rubocop:disable Naming/AccessorMethodName
      tag_list_was = channel.tag_list
      channel.tag_list = [] # clear existing tags
      begin
        channel.tag_list.add(params.dig(:channel, :tag_list), parser: ChannelTag::Parser)
        true
      rescue ChannelTag::ParseError
        channel.tag_list = tag_list_was # reset to original value
        false
      end
    end
  end
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

class ChannelsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :set_channel, only: [
    :show, :build_statistics, :update_snippet, :enable, :disable
  ]
  before_action -> {require_data(channels_url, Channel)}, only: [:build_all_statistics, :update_all_snippets]
  authorize_resource

  def index
    @search_channel = search_condition
    if turbo_frame_request?
      @channels = @search_channel.search
      render partial: 'search_results_frame', locals: {channels: @channels}
    else
      @path = request.fullpath
      respond_to do |format|
        format.html
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def build_statistics
    JobUtils.enqueue(Channels::BuildStatisticsJob, 'channel_id' => @channel.id)
    respond_to do |format|
      format.html {redirect_to @channel, notice: t('text.channel.build_statistics.start')}
      format.json {render json: {message: t('text.channel.build_statistics.start')}.to_json}
    end
  end

  def build_all_statistics
    JobUtils.enqueue(Channels::BuildAllStatisticsJob)
    respond_to do |format|
      format.html {redirect_to channels_url, notice: t('text.channel.build_all_statistics.start')}
      format.json {render json: {message: t('text.channel.build_all_statistics.start')}.to_json}
    end
  end

  def update_snippet
    JobUtils.enqueue(Channels::UpdateSnippetJob, 'channel_id' => @channel.id)
    respond_to do |format|
      format.html {redirect_to @channel, notice: t('text.channel.update_snippet.start')}
      format.json {render json: {message: t('text.channel.update_snippet.start')}.to_json}
    end
  end

  def update_all_snippets
    JobUtils.enqueue(Channels::UpdateAllSnippetsJob)
    respond_to do |format|
      format.html {redirect_to channels_url, notice: t('text.channel.update_all_snippets.start')}
      format.json {render json: {message: t('text.channel.update_all_snippets.start')}.to_json}
    end
  end

  def enable
    respond_to do |format|
      if @channel.update(disabled: false)
        format.html {redirect_to @channel, notice: t('text.channel.enable.succeeded')}
        format.json {render json: {message: t('text.channel.enable.succeeded')}.to_json}
      else
        format.html {redirect_to @channel, notice: t('text.channel.enable.failed')}
        format.json {render json: {message: t('text.channel.enable.failed')}.to_json}
      end
    end
  end

  def disable
    respond_to do |format|
      if @channel.update(disabled: true)
        format.html {redirect_to @channel, notice: t('text.channel.disable.succeeded')}
        format.json {render json: {message: t('text.channel.disable.succeeded')}.to_json}
      else
        format.html {redirect_to @channel, notice: t('text.channel.disable.failed')}
        format.json {render json: {message: t('text.channel.disable.failed')}.to_json}
      end
    end
  end

  protected

  def take_params
    super.merge(search_channel: search_params)
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def search_params
    search_channel = params.fetch(:search_channel, {})
    hash = {order: params[:order], direction: params[:direction]}
    attributes = [
      :title, :subscriber_count_from, :subscriber_count_to, :from_date, :to_date,
      :view_count_from, :view_count_to, :video_count_from, :video_count_to,
      :per, :disabled, :tag
    ]
    attributes.each_with_object(hash) {|attr, h| h[attr] = search_channel[attr]}.compact_blank
  end

  def search_condition
    cond = Search::Channel.new(search_params)
    cond.per ||= params[:per] || Channel::DEFAULT_PER
    cond.page = params[:page]
    cond
  end

  def sort_column
    params[:order] || 'subscriber_count'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end
end

app/views/channels/_action.html.erb
<%= link_to t('helpers.link.index'), channels_path(take_params),
            class: 'btn btn-info', role: :button %>
<% case controller.action_name %>
<% when 'show' %>
  <% if can?(:update, Channel) && @channel.disabled? %>
    <%= button_to t('helpers.link.enable'), enable_channel_path,
                  method: :put, class: 'btn btn-success', role: :button,
                  data: {disable_with: t('helpers.notice.processing'),
                         turbo_confirm: t('helpers.notice.enable_confirm')} %>
  <% end %>
  <% authenticated = SystemSetting.auth_configured? %>
  <% if can?(:update, Channel) && @channel.enabled? %>
    <%= button_to_if_enabled authenticated, t('helpers.link.update_snippet'), update_snippet_channel_path,
                             method: :put, class: 'btn btn-success', role: :button, id: 'update-snippet-btn',
                             data: {disable_with: t('helpers.notice.processing')}, remote: true %>
  <% end %>
  <% if can?(:create, ChannelStatistic) && @channel.enabled? %>
    <%= button_to_if_enabled authenticated, t('helpers.link.build_statistics'), build_statistics_channel_path,
                             method: :put, class: 'btn btn-success', role: :button, id: 'build-statistics-btn',
                             data: {disable_with: t('helpers.notice.processing')}, remote: true %>
  <% end %>
  <% if can?(:update, Channel) && @channel.enabled? %>
    <%= button_to t('helpers.link.disable'), disable_channel_path,
                  method: :put, class: 'btn btn-danger', role: :button,
                  data: {disable_with: t('helpers.notice.processing'),
                         turbo_confirm: t('helpers.notice.disable_confirm')} %>
  <% end %>
<% end %>

app/views/channels/_actions.html.erb
<% authenticated = SystemSetting.auth_configured? %>
<div>
  <% if can? :update, Channel %>
    <%= button_to_if_enabled authenticated, t('helpers.link.update_all_snippets'), update_all_snippets_channels_path,
                             method: :put, class: 'btn btn-success', role: :button, id: 'update-all-snippets-btn',
                             data: {disable_with: t('helpers.notice.processing')}, remote: true %>
  <% end %>
  <% if can? :create, ChannelStatistic %>
    <%= button_to_if_enabled authenticated, t('helpers.link.build_all_statistics'), build_all_statistics_channels_path,
                             method: :put, class: 'btn btn-success', role: :button, id: 'build-all-statistics-btn',
                             data: {disable_with: t('helpers.notice.processing')}, remote: true %>
  <% end %>
</div>
<div style="margin-top: 5px">
  <% if can? :create, Channel %>
    <% use_oauth2 = SystemSetting.use_oauth2?
       options = use_oauth2 ? {} : {data: {toggle: 'tooltip', 'bs-placement': 'bottom'}, title: t('helpers.notice.oauth2_required')} %>
    <%= tag.span(**options) do %>
      <%= button_to_if_enabled use_oauth2, t('helpers.link.create_from_subscription'), channel_lists_subscriptions_path,
                               method: :get, class: 'btn btn-info', role: :button %>
    <% end %>
    <%= button_to_if_enabled authenticated, t('helpers.link.create_from_search'), channel_lists_search_index_path,
                             method: :get, class: 'btn btn-info', role: :button %>
  <% end %>
</div>

app/views/channels/_search_form.html.erb
<%= form_with(model: search_channel, url: channels_path, method: :get, class: 'search', local: false,
              data: {turbo_frame: 'search-result-frame'}) do |form| %>
  <div class="container box_radius">
    <div class="row">
      <div class="col-12">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-lg-6">
        <div class="row">
          <%= form.label :subscriber_count %>
          <div class="col-5">
            <%= form.number_field :subscriber_count_from, class: 'form-control', min: 0 %>
          </div>
          <div class="col-2 text-center">～</div>
          <div class="col-5">
            <%= form.number_field :subscriber_count_to, class: 'form-control', min: 0 %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="row">
          <%= form.label :published_at %>
          <div class="col-5">
            <div class="input-group date-picker" data-wrap="true">
              <%= form.text_field :from_date, class: 'form-control', data: {input: true} %>
              <div class="input-group-text fa-icon" data-clear>
                <span class="fa fa-times"></span>
              </div>
            </div>
          </div>
          <div class="col-2 text-center">～</div>
          <div class="col-5">
            <div class="input-group date-picker" data-wrap="true">
              <%= form.text_field :to_date, class: 'form-control', data: {input: true} %>
              <div class="input-group-text fa-icon" data-clear>
                <span class="fa fa-times"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-lg-6">
        <div class="row">
          <%= form.label :view_count %>
          <div class="col-5">
            <%= form.number_field :view_count_from, class: 'form-control', min: 0 %>
          </div>
          <div class="col-2 text-center">～</div>
          <div class="col-5">
            <%= form.number_field :view_count_to, class: 'form-control', min: 0 %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="row">
          <%= form.label :video_count %>
          <div class="col-5">
            <%= form.number_field :video_count_from, class: 'form-control', min: 0 %>
          </div>
          <div class="col-2 text-center">～</div>
          <div class="col-5">
            <%= form.number_field :video_count_to, class: 'form-control', min: 0 %>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-6 col-md-3">
        <%= form.label :per %>
        <%= form.select :per, Channel::PER_LIST, {}, class: 'form-control form-select' %>
      </div>
      <div class="col-6 col-md-3">
        <%= form.label :disabled %>
        <%= form.select :disabled, Search::Channel.disabled_options, {}, class: 'form-control form-select' %>
      </div>
    </div>
    <div class="text-end">
      <%= button_tag t('helpers.button.reset'),
                     type: :button, id: 'reset-search', class: 'btn btn-secondary' %>
      <%= form.submit t('helpers.submit.search'), class: 'btn btn-success', name: nil %>
    </div>
  </div>
<% end %>

app/views/channels/_search_result.html.erb
<% if channels.present? %>
  <table class='table table-bordered table-hover table-striped'>
    <thead>
    <tr>
      <th></th>
      <th>
        <%= sortable Channel.human_attribute_name(:title), 'title', remote: true %>
      </th>
      <th class="d-none d-md-table-cell">
        <%= sortable Channel.human_attribute_name(:published_at), 'published_at', remote: true %>
      </th>
      <th>
        <%= sortable ChannelStatistic.human_attribute_name(:subscriber_count), 'subscriber_count', remote: true %>
      </th>
      <th class="d-none d-md-table-cell">
        <%= sortable ChannelStatistic.human_attribute_name(:view_count), 'view_count', remote: true %>
      </th>
      <th class="d-none d-md-table-cell">
        <%= sortable ChannelStatistic.human_attribute_name(:video_count), 'video_count', remote: true %>
      </th>
      <th class="d-none d-xl-table-cell">
        <%= sortable ChannelStatistic.human_attribute_name(:created_at), 'latest_acquired_at', remote: true %>
      </th>
    </tr>
    </thead>

    <tbody>
    <% channels.each do |c| %>
      <%= render partial: 'search_result_row', locals: {channel: c} %>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h4><%= t('text.channel.search.not_found') %></h4>
<% end %>

app/views/channels/_search_result_pagination.html.erb
<% if channels.present? %>
  <%= paginate channels, remote: true %>
<% end %>

app/views/channels/_search_result_row.html.erb
<tr>
  <td>
    <% if channel.thumbnail_url.present? %>
      <%= link_to(image_tag(channel.thumbnail_url), channel_path(channel, take_params)) %>
    <% end %>
  </td>
  <td>
    <% if channel.disabled? %>
      <span data-toggle="tooltip" title="<%= t('helpers.notice.channel_disabled') %>">⚠️</span>
    <% end %>
    <%= print_link(channel.title, channel_path(channel, take_params), t('text.channel.title.missing'), {data: {turbo_frame: '_top'}}) %>
    <div>
      <% channel.tags.each do |tag| %>
        <%= link_to(tag.name, channels_path(search_channel: {tag: tag.name}), class: 'badge rounded-pill bg-secondary', remote: true) %>
      <% end %>
    </div>
  </td>
  <td class="d-none d-md-table-cell">
    <%= tag.span print_datetime(channel.published_at, format: :date) %>
  </td>
  <td>
    <div class="vertical text-end text-nowrap">
      <span>
        <%= print_number(channel.latest_subscriber_count) %>
      </span>
      <span>
        <%= print_diff_numbers(channel.latest_subscriber_count, channel.second_latest_subscriber_count) %>
      </span>
    </div>
  </td>
  <td class="d-none d-md-table-cell">
    <div class="vertical text-end text-nowrap">
      <span>
        <%= print_number(channel.latest_view_count) %>
      </span>
      <span>
        <%= print_diff_numbers(channel.latest_view_count, channel.second_latest_view_count) %>
      </span>
    </div>
  </td>
  <td class="d-none d-md-table-cell">
    <div class="vertical text-end text-nowrap">
      <span>
        <%= print_number(channel.latest_video_count) %>
      </span>
      <span>
        <%= print_diff_numbers(channel.latest_video_count, channel.second_latest_video_count) %>
      </span>
    </div>
  </td>
  <td class="d-none d-xl-table-cell">
    <div class="vertical text-end text-nowrap">
      <span>
        <%= print_acquired_at(channel.latest_acquired_at, format: :date) %>
      </span>
      <span>
        <%= print_comparison_period(channel.latest_acquired_at, channel.second_latest_acquired_at) %>
      </span>
    </div>
  </td>
</tr>

app/views/channels/_snippets_frame.html.erb
<%= turbo_frame_tag 'snippets-frame' do %>
  <div id="search-snippets">
    <%= render partial: 'channels/snippets', locals: {channel_snippets: channel_snippets} %>
  </div>
<% end %>

app/views/channels/_statistics_frame.html.erb
<%= turbo_frame_tag 'statistics-frame' do %>
  <div id="search-statistics">
    <%= render partial: 'channels/statistics', locals: {channel_statistics: channel_statistics} %>
  </div>
<% end %>

app/views/channels/_tag_list.html.erb
<% if can?(:update, Channel) %>
  <%= button_to t('helpers.link.edit'), edit_tags_channel_path,
                method: :get, class: 'btn btn-sm btn-success', role: :button, remote: true %>
<% end %>
<% channel.tag_list.each do |tag| %>
  <%= link_to(tag, channels_path(search_channel: {tag: tag}), class: 'badge badge-pill badge-secondary') %>
<% end %>

app/views/channels/_warning_auth_not_configured.html.erb
<% if can?(:manage, SystemSetting) %>
  <% unless SystemSetting.auth_configured? %>
    <span class="fs-3 fw-bold text-danger">
      ⚠️
      <%= t('text.system_setting.auth_not_configured_html',
            href: link_to(t('text.system_setting.auth_not_configured_href'), system_setting_path)) %>
      ⚠️
    </span>
  <% end %>
<% end %>

app/views/channels/show.html.erb
<%= render partial: 'warning_auth_not_configured' %>
<% title = @channel.title.presence %>
<% content_for(:html_title) {title} %>

<h1>
  <%= t('helpers.title.show', model: Channel.model_name.human) %>
</h1>

<%= render partial: 'action' %>

<div class="container kinda-table">
  <div class="row">
    <div class="col-4 col-md-2 font-weight-bold">
      <%= Channel.human_attribute_name :title %>
    </div>
    <div class="col-8 col-md-10">
      <% if @channel.thumbnail_url.present? %>
        <%= link_to image_tag(@channel.thumbnail_url), @channel.url, target: '_blank', rel: 'noopener noreferrer' %>
      <% end %>
      <% if @channel.disabled? %>
        <span data-toggle="tooltip" title="<%= t('helpers.notice.channel_disabled') %>">⚠️</span>
      <% end %>
      <%= print_link(@channel.title, @channel.url, t('text.channel.title.missing'), target: '_blank', rel: 'noopener noreferrer') %>
    </div>
    <% if @channel.disabled? %>
      <div class="col-12 font-weight-bold text-danger">
        <%= t('text.channel.disabled_html') %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-4 col-md-2 font-weight-bold">
      <%= Channel.human_attribute_name :tags %>
    </div>
    <div class="channel tag-list col-8 col-md-10">
      <%= render partial: 'channels/tags/tag_list', locals: {channel: @channel} %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-md-2 font-weight-bold">
      <%= Channel.human_attribute_name :thumbnail_url %>
    </div>
    <% if @channel.thumbnail_url.present? %>
      <div class="col-2">
        <%= link_to 'Small', @channel.thumbnail_url, target: '_blank', rel: 'noopener noreferrer' %>
      </div>
      <div class="col-3" style="font-size: medium">
        <%= link_to 'Medium', @channel.medium_thumbnail_url, target: '_blank', rel: 'noopener noreferrer' %>
      </div>
      <div class="col-3" style="font-size: large">
        <%= link_to 'Large', @channel.high_thumbnail_url, target: '_blank', rel: 'noopener noreferrer' %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-4 col-md-2 font-weight-bold">
      <%= Channel.human_attribute_name :description %>
    </div>
    <div class="col-8 col-md-10 break-word-wrap">
      <%= simple_format text_url_to_link(@channel.description), {}, sanitize: false %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-md-2 font-weight-bold">
      <%= Channel.human_attribute_name :published_at %>
    </div>
    <div class="col-8 col-md-10">
      <%= print_datetime(@channel.published_at) %>
    </div>
  </div>
</div>

<%= turbo_frame_tag 'snippets-frame', src: channel_snippets_path(channel_id: @channel.id), loading: :lazy do %>
  <div id="search-snippets"></div>
  <%= render partial: 'partials/loader' %>
<% end %>

<%= turbo_frame_tag 'statistics-frame', src: channel_statistics_path(channel_id: @channel.id), loading: :lazy do %>
  <div id="search-statistics"></div>
  <%= render partial: 'partials/loader' %>
<% end %>